/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ResellerPackageService } from "../resellerPackage.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ResellerPackageCreateInput } from "./ResellerPackageCreateInput";
import { ResellerPackage } from "./ResellerPackage";
import { ResellerPackageFindManyArgs } from "./ResellerPackageFindManyArgs";
import { ResellerPackageWhereUniqueInput } from "./ResellerPackageWhereUniqueInput";
import { ResellerPackageUpdateInput } from "./ResellerPackageUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ResellerPackageControllerBase {
  constructor(
    protected readonly service: ResellerPackageService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ResellerPackage })
  @swagger.ApiBody({
    type: ResellerPackageCreateInput,
  })
  @nestAccessControl.UseRoles({
    resource: "ResellerPackage",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createResellerPackage(
    @common.Body() data: ResellerPackageCreateInput
  ): Promise<ResellerPackage> {
    return await this.service.createResellerPackage({
      data: {
        ...data,

        packageField: {
          connect: data.packageField,
        },

        reseller: {
          connect: data.reseller,
        },
      },
      select: {
        createdAt: true,
        id: true,
        isActive: true,

        packageField: {
          select: {
            id: true,
          },
        },

        reseller: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        wholesalePrice: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ResellerPackage] })
  @ApiNestedQuery(ResellerPackageFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ResellerPackage",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async resellerPackages(
    @common.Req() request: Request
  ): Promise<ResellerPackage[]> {
    const args = plainToClass(ResellerPackageFindManyArgs, request.query);
    return this.service.resellerPackages({
      ...args,
      select: {
        createdAt: true,
        id: true,
        isActive: true,

        packageField: {
          select: {
            id: true,
          },
        },

        reseller: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        wholesalePrice: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ResellerPackage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ResellerPackage",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async resellerPackage(
    @common.Param() params: ResellerPackageWhereUniqueInput
  ): Promise<ResellerPackage | null> {
    const result = await this.service.resellerPackage({
      where: params,
      select: {
        createdAt: true,
        id: true,
        isActive: true,

        packageField: {
          select: {
            id: true,
          },
        },

        reseller: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        wholesalePrice: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ResellerPackage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiBody({
    type: ResellerPackageUpdateInput,
  })
  @nestAccessControl.UseRoles({
    resource: "ResellerPackage",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateResellerPackage(
    @common.Param() params: ResellerPackageWhereUniqueInput,
    @common.Body() data: ResellerPackageUpdateInput
  ): Promise<ResellerPackage | null> {
    try {
      return await this.service.updateResellerPackage({
        where: params,
        data: {
          ...data,

          packageField: {
            connect: data.packageField,
          },

          reseller: {
            connect: data.reseller,
          },
        },
        select: {
          createdAt: true,
          id: true,
          isActive: true,

          packageField: {
            select: {
              id: true,
            },
          },

          reseller: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          wholesalePrice: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ResellerPackage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ResellerPackage",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteResellerPackage(
    @common.Param() params: ResellerPackageWhereUniqueInput
  ): Promise<ResellerPackage | null> {
    try {
      return await this.service.deleteResellerPackage({
        where: params,
        select: {
          createdAt: true,
          id: true,
          isActive: true,

          packageField: {
            select: {
              id: true,
            },
          },

          reseller: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          wholesalePrice: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
