/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  ProductItem as PrismaProductItem,
  Pop as PrismaPop,
  Product as PrismaProduct,
  Purchase as PrismaPurchase,
} from "@prisma/client";

export class ProductItemServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ProductItemCountArgs, "select">
  ): Promise<number> {
    return this.prisma.productItem.count(args);
  }

  async productItems(
    args: Prisma.ProductItemFindManyArgs
  ): Promise<PrismaProductItem[]> {
    return this.prisma.productItem.findMany(args);
  }
  async productItem(
    args: Prisma.ProductItemFindUniqueArgs
  ): Promise<PrismaProductItem | null> {
    return this.prisma.productItem.findUnique(args);
  }
  async createProductItem(
    args: Prisma.ProductItemCreateArgs
  ): Promise<PrismaProductItem> {
    return this.prisma.productItem.create(args);
  }
  async updateProductItem(
    args: Prisma.ProductItemUpdateArgs
  ): Promise<PrismaProductItem> {
    return this.prisma.productItem.update(args);
  }
  async deleteProductItem(
    args: Prisma.ProductItemDeleteArgs
  ): Promise<PrismaProductItem> {
    return this.prisma.productItem.delete(args);
  }

  async getLocationPop(parentId: string): Promise<PrismaPop | null> {
    return this.prisma.productItem
      .findUnique({
        where: { id: parentId },
      })
      .locationPop();
  }

  async getProduct(parentId: string): Promise<PrismaProduct | null> {
    return this.prisma.productItem
      .findUnique({
        where: { id: parentId },
      })
      .product();
  }

  async getPurchase(parentId: string): Promise<PrismaPurchase | null> {
    return this.prisma.productItem
      .findUnique({
        where: { id: parentId },
      })
      .purchase();
  }
}
