/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ProductItem } from "./ProductItem";
import { ProductItemCountArgs } from "./ProductItemCountArgs";
import { ProductItemFindManyArgs } from "./ProductItemFindManyArgs";
import { ProductItemFindUniqueArgs } from "./ProductItemFindUniqueArgs";
import { CreateProductItemArgs } from "./CreateProductItemArgs";
import { UpdateProductItemArgs } from "./UpdateProductItemArgs";
import { DeleteProductItemArgs } from "./DeleteProductItemArgs";
import { Pop } from "../../pop/base/Pop";
import { Product } from "../../product/base/Product";
import { Purchase } from "../../purchase/base/Purchase";
import { ProductItemService } from "../productItem.service";
@graphql.Resolver(() => ProductItem)
export class ProductItemResolverBase {
  constructor(protected readonly service: ProductItemService) {}

  async _productItemsMeta(
    @graphql.Args() args: ProductItemCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ProductItem])
  async productItems(
    @graphql.Args() args: ProductItemFindManyArgs
  ): Promise<ProductItem[]> {
    return this.service.productItems(args);
  }

  @graphql.Query(() => ProductItem, { nullable: true })
  async productItem(
    @graphql.Args() args: ProductItemFindUniqueArgs
  ): Promise<ProductItem | null> {
    const result = await this.service.productItem(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ProductItem)
  async createProductItem(
    @graphql.Args() args: CreateProductItemArgs
  ): Promise<ProductItem> {
    return await this.service.createProductItem({
      ...args,
      data: {
        ...args.data,

        locationPop: args.data.locationPop
          ? {
              connect: args.data.locationPop,
            }
          : undefined,

        product: {
          connect: args.data.product,
        },

        purchase: args.data.purchase
          ? {
              connect: args.data.purchase,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => ProductItem)
  async updateProductItem(
    @graphql.Args() args: UpdateProductItemArgs
  ): Promise<ProductItem | null> {
    try {
      return await this.service.updateProductItem({
        ...args,
        data: {
          ...args.data,

          locationPop: args.data.locationPop
            ? {
                connect: args.data.locationPop,
              }
            : undefined,

          product: {
            connect: args.data.product,
          },

          purchase: args.data.purchase
            ? {
                connect: args.data.purchase,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ProductItem)
  async deleteProductItem(
    @graphql.Args() args: DeleteProductItemArgs
  ): Promise<ProductItem | null> {
    try {
      return await this.service.deleteProductItem(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Pop, {
    nullable: true,
    name: "locationPop",
  })
  async getLocationPop(
    @graphql.Parent() parent: ProductItem
  ): Promise<Pop | null> {
    const result = await this.service.getLocationPop(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Product, {
    nullable: true,
    name: "product",
  })
  async getProduct(
    @graphql.Parent() parent: ProductItem
  ): Promise<Product | null> {
    const result = await this.service.getProduct(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Purchase, {
    nullable: true,
    name: "purchase",
  })
  async getPurchase(
    @graphql.Parent() parent: ProductItem
  ): Promise<Purchase | null> {
    const result = await this.service.getPurchase(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
