/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  IsString,
  IsBoolean,
  ValidateNested,
  IsOptional,
  MaxLength,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { Pop } from "../../pop/base/Pop";
import { Product } from "../../product/base/Product";
import { Purchase } from "../../purchase/base/Purchase";
import { EnumProductItemStatus } from "./EnumProductItemStatus";

@ObjectType()
class ProductItem {
  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isUsedProduct!: boolean;

  @ApiProperty({
    required: false,
    type: () => Pop,
  })
  @ValidateNested()
  @Type(() => Pop)
  @IsOptional()
  locationPop?: Pop | null;

  @ApiProperty({
    required: true,
    type: () => Product,
  })
  @ValidateNested()
  @Type(() => Product)
  product?: Product;

  @ApiProperty({
    required: false,
    type: () => Purchase,
  })
  @ValidateNested()
  @Type(() => Purchase)
  @IsOptional()
  purchase?: Purchase | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  serialNumber!: string;

  @ApiProperty({
    required: true,
    enum: EnumProductItemStatus,
  })
  @IsEnum(EnumProductItemStatus)
  @Field(() => EnumProductItemStatus, {
    nullable: true,
  })
  status?: "IN_STOCK" | "SOLD" | "DEPLOYED" | "RETURNED" | "DAMAGED";

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { ProductItem as ProductItem };
