/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { TokenCategory } from "./TokenCategory";
import { TokenCategoryCountArgs } from "./TokenCategoryCountArgs";
import { TokenCategoryFindManyArgs } from "./TokenCategoryFindManyArgs";
import { TokenCategoryFindUniqueArgs } from "./TokenCategoryFindUniqueArgs";
import { CreateTokenCategoryArgs } from "./CreateTokenCategoryArgs";
import { UpdateTokenCategoryArgs } from "./UpdateTokenCategoryArgs";
import { DeleteTokenCategoryArgs } from "./DeleteTokenCategoryArgs";
import { TokenFindManyArgs } from "../../token/base/TokenFindManyArgs";
import { Token } from "../../token/base/Token";
import { TokenCategoryService } from "../tokenCategory.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => TokenCategory)
export class TokenCategoryResolverBase {
  constructor(
    protected readonly service: TokenCategoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "TokenCategory",
    action: "read",
    possession: "any",
  })
  async _tokenCategoriesMeta(
    @graphql.Args() args: TokenCategoryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [TokenCategory])
  @nestAccessControl.UseRoles({
    resource: "TokenCategory",
    action: "read",
    possession: "any",
  })
  async tokenCategories(
    @graphql.Args() args: TokenCategoryFindManyArgs
  ): Promise<TokenCategory[]> {
    return this.service.tokenCategories(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => TokenCategory, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "TokenCategory",
    action: "read",
    possession: "own",
  })
  async tokenCategory(
    @graphql.Args() args: TokenCategoryFindUniqueArgs
  ): Promise<TokenCategory | null> {
    const result = await this.service.tokenCategory(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => TokenCategory)
  @nestAccessControl.UseRoles({
    resource: "TokenCategory",
    action: "create",
    possession: "any",
  })
  async createTokenCategory(
    @graphql.Args() args: CreateTokenCategoryArgs
  ): Promise<TokenCategory> {
    return await this.service.createTokenCategory({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => TokenCategory)
  @nestAccessControl.UseRoles({
    resource: "TokenCategory",
    action: "update",
    possession: "any",
  })
  async updateTokenCategory(
    @graphql.Args() args: UpdateTokenCategoryArgs
  ): Promise<TokenCategory | null> {
    try {
      return await this.service.updateTokenCategory({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => TokenCategory)
  @nestAccessControl.UseRoles({
    resource: "TokenCategory",
    action: "delete",
    possession: "any",
  })
  async deleteTokenCategory(
    @graphql.Args() args: DeleteTokenCategoryArgs
  ): Promise<TokenCategory | null> {
    try {
      return await this.service.deleteTokenCategory(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Token], { name: "tokens" })
  @nestAccessControl.UseRoles({
    resource: "Token",
    action: "read",
    possession: "any",
  })
  async findTokens(
    @graphql.Parent() parent: TokenCategory,
    @graphql.Args() args: TokenFindManyArgs
  ): Promise<Token[]> {
    const results = await this.service.findTokens(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
