/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ResellerPackageListRelationFilter } from "../../resellerPackage/base/ResellerPackageListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { DecimalFilter } from "../../util/DecimalFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { StringFilter } from "../../util/StringFilter";
import { PopListRelationFilter } from "../../pop/base/PopListRelationFilter";
import { ResellerRechargeLogListRelationFilter } from "../../resellerRechargeLog/base/ResellerRechargeLogListRelationFilter";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class ResellerWhereInput {
  @ApiProperty({
    required: false,
    type: () => ResellerPackageListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ResellerPackageListRelationFilter)
  @IsOptional()
  @Field(() => ResellerPackageListRelationFilter, {
    nullable: true,
  })
  assignedPackages?: ResellerPackageListRelationFilter;

  @ApiProperty({
    required: false,
    type: DecimalFilter,
  })
  @Type(() => DecimalFilter)
  @IsOptional()
  @Field(() => DecimalFilter, {
    nullable: true,
  })
  balance?: DecimalFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  businessName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  createdAt?: DateTimeFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => PopListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PopListRelationFilter)
  @IsOptional()
  @Field(() => PopListRelationFilter, {
    nullable: true,
  })
  pops?: PopListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ResellerRechargeLogListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ResellerRechargeLogListRelationFilter)
  @IsOptional()
  @Field(() => ResellerRechargeLogListRelationFilter, {
    nullable: true,
  })
  rechargeLogs?: ResellerRechargeLogListRelationFilter;

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  updatedAt?: DateTimeFilter;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput;
}

export { ResellerWhereInput as ResellerWhereInput };
