/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Reseller } from "./Reseller";
import { ResellerCountArgs } from "./ResellerCountArgs";
import { ResellerFindManyArgs } from "./ResellerFindManyArgs";
import { ResellerFindUniqueArgs } from "./ResellerFindUniqueArgs";
import { CreateResellerArgs } from "./CreateResellerArgs";
import { UpdateResellerArgs } from "./UpdateResellerArgs";
import { DeleteResellerArgs } from "./DeleteResellerArgs";
import { PopFindManyArgs } from "../../pop/base/PopFindManyArgs";
import { Pop } from "../../pop/base/Pop";
import { ResellerRechargeLogFindManyArgs } from "../../resellerRechargeLog/base/ResellerRechargeLogFindManyArgs";
import { ResellerRechargeLog } from "../../resellerRechargeLog/base/ResellerRechargeLog";
import { User } from "../../user/base/User";
import { ResellerService } from "../reseller.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Reseller)
export class ResellerResolverBase {
  constructor(
    protected readonly service: ResellerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Reseller",
    action: "read",
    possession: "any",
  })
  async _resellersMeta(
    @graphql.Args() args: ResellerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Reseller])
  @nestAccessControl.UseRoles({
    resource: "Reseller",
    action: "read",
    possession: "any",
  })
  async resellers(
    @graphql.Args() args: ResellerFindManyArgs
  ): Promise<Reseller[]> {
    return this.service.resellers(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Reseller, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Reseller",
    action: "read",
    possession: "own",
  })
  async reseller(
    @graphql.Args() args: ResellerFindUniqueArgs
  ): Promise<Reseller | null> {
    const result = await this.service.reseller(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Reseller)
  @nestAccessControl.UseRoles({
    resource: "Reseller",
    action: "create",
    possession: "any",
  })
  async createReseller(
    @graphql.Args() args: CreateResellerArgs
  ): Promise<Reseller> {
    return await this.service.createReseller({
      ...args,
      data: {
        ...args.data,

        user: {
          connect: args.data.user,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Reseller)
  @nestAccessControl.UseRoles({
    resource: "Reseller",
    action: "update",
    possession: "any",
  })
  async updateReseller(
    @graphql.Args() args: UpdateResellerArgs
  ): Promise<Reseller | null> {
    try {
      return await this.service.updateReseller({
        ...args,
        data: {
          ...args.data,

          user: {
            connect: args.data.user,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Reseller)
  @nestAccessControl.UseRoles({
    resource: "Reseller",
    action: "delete",
    possession: "any",
  })
  async deleteReseller(
    @graphql.Args() args: DeleteResellerArgs
  ): Promise<Reseller | null> {
    try {
      return await this.service.deleteReseller(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Pop], { name: "pops" })
  @nestAccessControl.UseRoles({
    resource: "Pop",
    action: "read",
    possession: "any",
  })
  async findPops(
    @graphql.Parent() parent: Reseller,
    @graphql.Args() args: PopFindManyArgs
  ): Promise<Pop[]> {
    const results = await this.service.findPops(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [ResellerRechargeLog], { name: "rechargeLogs" })
  @nestAccessControl.UseRoles({
    resource: "ResellerRechargeLog",
    action: "read",
    possession: "any",
  })
  async findRechargeLogs(
    @graphql.Parent() parent: Reseller,
    @graphql.Args() args: ResellerRechargeLogFindManyArgs
  ): Promise<ResellerRechargeLog[]> {
    const results = await this.service.findRechargeLogs(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: Reseller): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
