/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field, Float } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ResellerPackage } from "../../resellerPackage/base/ResellerPackage";
import {
  ValidateNested,
  IsOptional,
  IsNumber,
  Max,
  IsString,
  MaxLength,
  IsDate,
} from "class-validator";
import { Type } from "class-transformer";
import { Decimal } from "decimal.js";
import { Pop } from "../../pop/base/Pop";
import { ResellerRechargeLog } from "../../resellerRechargeLog/base/ResellerRechargeLog";
import { User } from "../../user/base/User";

@ObjectType()
class Reseller {
  @ApiProperty({
    required: false,
    type: () => [ResellerPackage],
  })
  @ValidateNested()
  @Type(() => ResellerPackage)
  @IsOptional()
  assignedPackages?: Array<ResellerPackage>;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @Field(() => Float)
  balance!: Decimal;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  businessName!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: () => [Pop],
  })
  @ValidateNested()
  @Type(() => Pop)
  @IsOptional()
  pops?: Array<Pop>;

  @ApiProperty({
    required: false,
    type: () => [ResellerRechargeLog],
  })
  @ValidateNested()
  @Type(() => ResellerRechargeLog)
  @IsOptional()
  rechargeLogs?: Array<ResellerRechargeLog>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: true,
    type: () => User,
  })
  @ValidateNested()
  @Type(() => User)
  user?: User;
}

export { Reseller as Reseller };
