/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { SmsTemplate } from "./SmsTemplate";
import { SmsTemplateCountArgs } from "./SmsTemplateCountArgs";
import { SmsTemplateFindManyArgs } from "./SmsTemplateFindManyArgs";
import { SmsTemplateFindUniqueArgs } from "./SmsTemplateFindUniqueArgs";
import { CreateSmsTemplateArgs } from "./CreateSmsTemplateArgs";
import { UpdateSmsTemplateArgs } from "./UpdateSmsTemplateArgs";
import { DeleteSmsTemplateArgs } from "./DeleteSmsTemplateArgs";
import { SmsTemplateService } from "../smsTemplate.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => SmsTemplate)
export class SmsTemplateResolverBase {
  constructor(
    protected readonly service: SmsTemplateService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "SmsTemplate",
    action: "read",
    possession: "any",
  })
  async _smsTemplatesMeta(
    @graphql.Args() args: SmsTemplateCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [SmsTemplate])
  @nestAccessControl.UseRoles({
    resource: "SmsTemplate",
    action: "read",
    possession: "any",
  })
  async smsTemplates(
    @graphql.Args() args: SmsTemplateFindManyArgs
  ): Promise<SmsTemplate[]> {
    return this.service.smsTemplates(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => SmsTemplate, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SmsTemplate",
    action: "read",
    possession: "own",
  })
  async smsTemplate(
    @graphql.Args() args: SmsTemplateFindUniqueArgs
  ): Promise<SmsTemplate | null> {
    const result = await this.service.smsTemplate(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => SmsTemplate)
  @nestAccessControl.UseRoles({
    resource: "SmsTemplate",
    action: "create",
    possession: "any",
  })
  async createSmsTemplate(
    @graphql.Args() args: CreateSmsTemplateArgs
  ): Promise<SmsTemplate> {
    return await this.service.createSmsTemplate({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => SmsTemplate)
  @nestAccessControl.UseRoles({
    resource: "SmsTemplate",
    action: "update",
    possession: "any",
  })
  async updateSmsTemplate(
    @graphql.Args() args: UpdateSmsTemplateArgs
  ): Promise<SmsTemplate | null> {
    try {
      return await this.service.updateSmsTemplate({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SmsTemplate)
  @nestAccessControl.UseRoles({
    resource: "SmsTemplate",
    action: "delete",
    possession: "any",
  })
  async deleteSmsTemplate(
    @graphql.Args() args: DeleteSmsTemplateArgs
  ): Promise<SmsTemplate | null> {
    try {
      return await this.service.deleteSmsTemplate(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
