/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SmsTemplateService } from "../smsTemplate.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SmsTemplateCreateInput } from "./SmsTemplateCreateInput";
import { SmsTemplate } from "./SmsTemplate";
import { SmsTemplateFindManyArgs } from "./SmsTemplateFindManyArgs";
import { SmsTemplateWhereUniqueInput } from "./SmsTemplateWhereUniqueInput";
import { SmsTemplateUpdateInput } from "./SmsTemplateUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SmsTemplateControllerBase {
  constructor(
    protected readonly service: SmsTemplateService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SmsTemplate })
  @swagger.ApiBody({
    type: SmsTemplateCreateInput,
  })
  @nestAccessControl.UseRoles({
    resource: "SmsTemplate",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSmsTemplate(
    @common.Body() data: SmsTemplateCreateInput
  ): Promise<SmsTemplate> {
    return await this.service.createSmsTemplate({
      data: data,
      select: {
        content: true,
        createdAt: true,
        id: true,
        isActive: true,
        name: true,
        type: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SmsTemplate] })
  @ApiNestedQuery(SmsTemplateFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SmsTemplate",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async smsTemplates(@common.Req() request: Request): Promise<SmsTemplate[]> {
    const args = plainToClass(SmsTemplateFindManyArgs, request.query);
    return this.service.smsTemplates({
      ...args,
      select: {
        content: true,
        createdAt: true,
        id: true,
        isActive: true,
        name: true,
        type: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SmsTemplate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SmsTemplate",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async smsTemplate(
    @common.Param() params: SmsTemplateWhereUniqueInput
  ): Promise<SmsTemplate | null> {
    const result = await this.service.smsTemplate({
      where: params,
      select: {
        content: true,
        createdAt: true,
        id: true,
        isActive: true,
        name: true,
        type: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SmsTemplate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiBody({
    type: SmsTemplateUpdateInput,
  })
  @nestAccessControl.UseRoles({
    resource: "SmsTemplate",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSmsTemplate(
    @common.Param() params: SmsTemplateWhereUniqueInput,
    @common.Body() data: SmsTemplateUpdateInput
  ): Promise<SmsTemplate | null> {
    try {
      return await this.service.updateSmsTemplate({
        where: params,
        data: data,
        select: {
          content: true,
          createdAt: true,
          id: true,
          isActive: true,
          name: true,
          type: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SmsTemplate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SmsTemplate",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSmsTemplate(
    @common.Param() params: SmsTemplateWhereUniqueInput
  ): Promise<SmsTemplate | null> {
    try {
      return await this.service.deleteSmsTemplate({
        where: params,
        select: {
          content: true,
          createdAt: true,
          id: true,
          isActive: true,
          name: true,
          type: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
