/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, SmsTemplate as PrismaSmsTemplate } from "@prisma/client";

export class SmsTemplateServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.SmsTemplateCountArgs, "select">
  ): Promise<number> {
    return this.prisma.smsTemplate.count(args);
  }

  async smsTemplates(
    args: Prisma.SmsTemplateFindManyArgs
  ): Promise<PrismaSmsTemplate[]> {
    return this.prisma.smsTemplate.findMany(args);
  }
  async smsTemplate(
    args: Prisma.SmsTemplateFindUniqueArgs
  ): Promise<PrismaSmsTemplate | null> {
    return this.prisma.smsTemplate.findUnique(args);
  }
  async createSmsTemplate(
    args: Prisma.SmsTemplateCreateArgs
  ): Promise<PrismaSmsTemplate> {
    return this.prisma.smsTemplate.create(args);
  }
  async updateSmsTemplate(
    args: Prisma.SmsTemplateUpdateArgs
  ): Promise<PrismaSmsTemplate> {
    return this.prisma.smsTemplate.update(args);
  }
  async deleteSmsTemplate(
    args: Prisma.SmsTemplateDeleteArgs
  ): Promise<PrismaSmsTemplate> {
    return this.prisma.smsTemplate.delete(args);
  }
}
