/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field, Float } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsNumber,
  Max,
  IsInt,
  IsEnum,
  IsBoolean,
  IsDate,
} from "class-validator";

import { AreaWhereUniqueInput } from "../../area/base/AreaWhereUniqueInput";
import { Type } from "class-transformer";
import { Decimal } from "decimal.js";
import { BillSheetCreateNestedManyWithoutCustomersInput } from "./BillSheetCreateNestedManyWithoutCustomersInput";
import { PackageModelWhereUniqueInput } from "../../packageModel/base/PackageModelWhereUniqueInput";
import { PopWhereUniqueInput } from "../../pop/base/PopWhereUniqueInput";
import { EnumCustomerStatus } from "./EnumCustomerStatus";
import { TokenCreateNestedManyWithoutCustomersInput } from "./TokenCreateNestedManyWithoutCustomersInput";
import { TransactionCreateNestedManyWithoutCustomersInput } from "./TransactionCreateNestedManyWithoutCustomersInput";

@InputType()
class CustomerCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: () => AreaWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AreaWhereUniqueInput)
  @IsOptional()
  @Field(() => AreaWhereUniqueInput, {
    nullable: true,
  })
  area?: AreaWhereUniqueInput | null;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @Field(() => Float)
  balance!: Decimal;

  @ApiProperty({
    required: false,
    type: () => BillSheetCreateNestedManyWithoutCustomersInput,
  })
  @ValidateNested()
  @Type(() => BillSheetCreateNestedManyWithoutCustomersInput)
  @IsOptional()
  @Field(() => BillSheetCreateNestedManyWithoutCustomersInput, {
    nullable: true,
  })
  billSheets?: BillSheetCreateNestedManyWithoutCustomersInput;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @Field(() => Number)
  billingCycle!: number;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  customerId!: string;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @Field(() => Float)
  dueAmount!: Decimal;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  ipAddress?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  macAddress?: string | null;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @Field(() => Float)
  monthlyBill!: Decimal;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nid?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  onuMac?: string | null;

  @ApiProperty({
    required: true,
    type: () => PackageModelWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PackageModelWhereUniqueInput)
  @Field(() => PackageModelWhereUniqueInput)
  packageField!: PackageModelWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  phone!: string;

  @ApiProperty({
    required: true,
    type: () => PopWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PopWhereUniqueInput)
  @Field(() => PopWhereUniqueInput)
  pop!: PopWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  pppoePassword?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  pppoeUsername?: string | null;

  @ApiProperty({
    required: true,
    enum: EnumCustomerStatus,
  })
  @IsEnum(EnumCustomerStatus)
  @Field(() => EnumCustomerStatus)
  status!:
    | "ACTIVE"
    | "INACTIVE"
    | "EXPIRED"
    | "PENDING"
    | "DELETED"
    | "DISCONNECTED";

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  tempExtensionActive!: boolean;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  tempExtensionExpiresAt?: Date | null;

  @ApiProperty({
    required: false,
    type: () => TokenCreateNestedManyWithoutCustomersInput,
  })
  @ValidateNested()
  @Type(() => TokenCreateNestedManyWithoutCustomersInput)
  @IsOptional()
  @Field(() => TokenCreateNestedManyWithoutCustomersInput, {
    nullable: true,
  })
  tokens?: TokenCreateNestedManyWithoutCustomersInput;

  @ApiProperty({
    required: false,
    type: () => TransactionCreateNestedManyWithoutCustomersInput,
  })
  @ValidateNested()
  @Type(() => TransactionCreateNestedManyWithoutCustomersInput)
  @IsOptional()
  @Field(() => TransactionCreateNestedManyWithoutCustomersInput, {
    nullable: true,
  })
  transactions?: TransactionCreateNestedManyWithoutCustomersInput;
}

export { CustomerCreateInput as CustomerCreateInput };
