/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Customer as PrismaCustomer,
  BillSheet as PrismaBillSheet,
  Token as PrismaToken,
  Transaction as PrismaTransaction,
  Area as PrismaArea,
  PackageModel as PrismaPackageModel,
  Pop as PrismaPop,
} from "@prisma/client";

export class CustomerServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.CustomerCountArgs, "select">): Promise<number> {
    return this.prisma.customer.count(args);
  }

  async customers(
    args: Prisma.CustomerFindManyArgs
  ): Promise<PrismaCustomer[]> {
    return this.prisma.customer.findMany(args);
  }
  async customer(
    args: Prisma.CustomerFindUniqueArgs
  ): Promise<PrismaCustomer | null> {
    return this.prisma.customer.findUnique(args);
  }
  async createCustomer(
    args: Prisma.CustomerCreateArgs
  ): Promise<PrismaCustomer> {
    return this.prisma.customer.create(args);
  }
  async updateCustomer(
    args: Prisma.CustomerUpdateArgs
  ): Promise<PrismaCustomer> {
    return this.prisma.customer.update(args);
  }
  async deleteCustomer(
    args: Prisma.CustomerDeleteArgs
  ): Promise<PrismaCustomer> {
    return this.prisma.customer.delete(args);
  }

  async findBillSheets(
    parentId: string,
    args: Prisma.BillSheetFindManyArgs
  ): Promise<PrismaBillSheet[]> {
    return this.prisma.customer
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .billSheets(args);
  }

  async findTokens(
    parentId: string,
    args: Prisma.TokenFindManyArgs
  ): Promise<PrismaToken[]> {
    return this.prisma.customer
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .tokens(args);
  }

  async findTransactions(
    parentId: string,
    args: Prisma.TransactionFindManyArgs
  ): Promise<PrismaTransaction[]> {
    return this.prisma.customer
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .transactions(args);
  }

  async getArea(parentId: string): Promise<PrismaArea | null> {
    return this.prisma.customer
      .findUnique({
        where: { id: parentId },
      })
      .area();
  }

  async getPackageField(parentId: string): Promise<PrismaPackageModel | null> {
    return this.prisma.customer
      .findUnique({
        where: { id: parentId },
      })
      .packageField();
  }

  async getPop(parentId: string): Promise<PrismaPop | null> {
    return this.prisma.customer
      .findUnique({
        where: { id: parentId },
      })
      .pop();
  }
}
