/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Customer } from "./Customer";
import { CustomerCountArgs } from "./CustomerCountArgs";
import { CustomerFindManyArgs } from "./CustomerFindManyArgs";
import { CustomerFindUniqueArgs } from "./CustomerFindUniqueArgs";
import { CreateCustomerArgs } from "./CreateCustomerArgs";
import { UpdateCustomerArgs } from "./UpdateCustomerArgs";
import { DeleteCustomerArgs } from "./DeleteCustomerArgs";
import { BillSheetFindManyArgs } from "../../billSheet/base/BillSheetFindManyArgs";
import { BillSheet } from "../../billSheet/base/BillSheet";
import { TokenFindManyArgs } from "../../token/base/TokenFindManyArgs";
import { Token } from "../../token/base/Token";
import { TransactionFindManyArgs } from "../../transaction/base/TransactionFindManyArgs";
import { Transaction } from "../../transaction/base/Transaction";
import { Area } from "../../area/base/Area";
import { PackageModel } from "../../packageModel/base/PackageModel";
import { Pop } from "../../pop/base/Pop";
import { CustomerService } from "../customer.service";
@graphql.Resolver(() => Customer)
export class CustomerResolverBase {
  constructor(protected readonly service: CustomerService) {}

  async _customersMeta(
    @graphql.Args() args: CustomerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Customer])
  async customers(
    @graphql.Args() args: CustomerFindManyArgs
  ): Promise<Customer[]> {
    return this.service.customers(args);
  }

  @graphql.Query(() => Customer, { nullable: true })
  async customer(
    @graphql.Args() args: CustomerFindUniqueArgs
  ): Promise<Customer | null> {
    const result = await this.service.customer(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Customer)
  async createCustomer(
    @graphql.Args() args: CreateCustomerArgs
  ): Promise<Customer> {
    return await this.service.createCustomer({
      ...args,
      data: {
        ...args.data,

        area: args.data.area
          ? {
              connect: args.data.area,
            }
          : undefined,

        packageField: {
          connect: args.data.packageField,
        },

        pop: {
          connect: args.data.pop,
        },
      },
    });
  }

  @graphql.Mutation(() => Customer)
  async updateCustomer(
    @graphql.Args() args: UpdateCustomerArgs
  ): Promise<Customer | null> {
    try {
      return await this.service.updateCustomer({
        ...args,
        data: {
          ...args.data,

          area: args.data.area
            ? {
                connect: args.data.area,
              }
            : undefined,

          packageField: {
            connect: args.data.packageField,
          },

          pop: {
            connect: args.data.pop,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Customer)
  async deleteCustomer(
    @graphql.Args() args: DeleteCustomerArgs
  ): Promise<Customer | null> {
    try {
      return await this.service.deleteCustomer(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [BillSheet], { name: "billSheets" })
  async findBillSheets(
    @graphql.Parent() parent: Customer,
    @graphql.Args() args: BillSheetFindManyArgs
  ): Promise<BillSheet[]> {
    const results = await this.service.findBillSheets(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Token], { name: "tokens" })
  async findTokens(
    @graphql.Parent() parent: Customer,
    @graphql.Args() args: TokenFindManyArgs
  ): Promise<Token[]> {
    const results = await this.service.findTokens(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Transaction], { name: "transactions" })
  async findTransactions(
    @graphql.Parent() parent: Customer,
    @graphql.Args() args: TransactionFindManyArgs
  ): Promise<Transaction[]> {
    const results = await this.service.findTransactions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Area, {
    nullable: true,
    name: "area",
  })
  async getArea(@graphql.Parent() parent: Customer): Promise<Area | null> {
    const result = await this.service.getArea(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => PackageModel, {
    nullable: true,
    name: "packageField",
  })
  async getPackageField(
    @graphql.Parent() parent: Customer
  ): Promise<PackageModel | null> {
    const result = await this.service.getPackageField(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Pop, {
    nullable: true,
    name: "pop",
  })
  async getPop(@graphql.Parent() parent: Customer): Promise<Pop | null> {
    const result = await this.service.getPop(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
