/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AccountCreateNestedManyWithoutUsersInput } from "./AccountCreateNestedManyWithoutUsersInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  IsDate,
  MaxLength,
  IsBoolean,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { ActivityLogCreateNestedManyWithoutUsersInput } from "./ActivityLogCreateNestedManyWithoutUsersInput";
import { SupportTicketCreateNestedManyWithoutUsersInput } from "./SupportTicketCreateNestedManyWithoutUsersInput";
import { TransactionCreateNestedManyWithoutUsersInput } from "./TransactionCreateNestedManyWithoutUsersInput";
import { EmployeeWhereUniqueInput } from "../../employee/base/EmployeeWhereUniqueInput";
import { ExpenseCreateNestedManyWithoutUsersInput } from "./ExpenseCreateNestedManyWithoutUsersInput";
import { InvoiceCreateNestedManyWithoutUsersInput } from "./InvoiceCreateNestedManyWithoutUsersInput";
import { MarketingLeadCreateNestedManyWithoutUsersInput } from "./MarketingLeadCreateNestedManyWithoutUsersInput";
import { UserPermissionCreateNestedManyWithoutUsersInput } from "./UserPermissionCreateNestedManyWithoutUsersInput";
import { PopRechargeCreateNestedManyWithoutUsersInput } from "./PopRechargeCreateNestedManyWithoutUsersInput";
import { ResellerWhereUniqueInput } from "../../reseller/base/ResellerWhereUniqueInput";
import { EnumUserRoles } from "./EnumUserRoles";
import { SessionCreateNestedManyWithoutUsersInput } from "./SessionCreateNestedManyWithoutUsersInput";
import { SubscriptionCreateNestedManyWithoutUsersInput } from "./SubscriptionCreateNestedManyWithoutUsersInput";
import { TokenCreateNestedManyWithoutUsersInput } from "./TokenCreateNestedManyWithoutUsersInput";
import { UsageCreateNestedManyWithoutUsersInput } from "./UsageCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => AccountCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AccountCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AccountCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  accounts?: AccountCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => ActivityLogCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ActivityLogCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ActivityLogCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  activityLogs?: ActivityLogCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => SupportTicketCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SupportTicketCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SupportTicketCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  assignedTickets?: SupportTicketCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => TransactionCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TransactionCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TransactionCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  collectedBills?: TransactionCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  emailVerified?: Date | null;

  @ApiProperty({
    required: false,
    type: () => EmployeeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => EmployeeWhereUniqueInput)
  @IsOptional()
  @Field(() => EmployeeWhereUniqueInput, {
    nullable: true,
  })
  employeeProfile?: EmployeeWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ExpenseCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ExpenseCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ExpenseCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  expenses?: ExpenseCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  image?: string | null;

  @ApiProperty({
    required: false,
    type: () => InvoiceCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => InvoiceCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => InvoiceCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  invoices?: InvoiceCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isActive!: boolean;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => MarketingLeadCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => MarketingLeadCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => MarketingLeadCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  marketingLeads?: MarketingLeadCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserPermissionCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserPermissionCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserPermissionCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  permissions?: UserPermissionCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;

  @ApiProperty({
    required: false,
    type: () => PopRechargeCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => PopRechargeCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => PopRechargeCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  popRecharges?: PopRechargeCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => ResellerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ResellerWhereUniqueInput)
  @IsOptional()
  @Field(() => ResellerWhereUniqueInput, {
    nullable: true,
  })
  resellerProfile?: ResellerWhereUniqueInput | null;

  @ApiProperty({
    required: true,
    enum: EnumUserRoles,
  })
  @IsEnum(EnumUserRoles)
  @Field(() => EnumUserRoles)
  roles!:
    | "USER"
    | "ADMIN"
    | "SUPER_ADMIN"
    | "MANAGER"
    | "ACCOUNTANT"
    | "SUPPORT"
    | "CABLE_TEAM"
    | "BILL_MAN"
    | "MARKETING_AGENT"
    | "RESELLER"
    | "SUB_RESELLER";

  @ApiProperty({
    required: false,
    type: () => SessionCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SessionCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SessionCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  sessions?: SessionCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => SubscriptionCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SubscriptionCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SubscriptionCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  subscriptions?: SubscriptionCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => TokenCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TokenCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TokenCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  supportTickets?: TokenCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => SupportTicketCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SupportTicketCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SupportTicketCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  tickets?: SupportTicketCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => UsageCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UsageCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UsageCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  usages?: UsageCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string | null;
}

export { UserCreateInput as UserCreateInput };
