/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AccountUpdateManyWithoutUsersInput } from "./AccountUpdateManyWithoutUsersInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  IsDate,
  MaxLength,
  IsBoolean,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { ActivityLogUpdateManyWithoutUsersInput } from "./ActivityLogUpdateManyWithoutUsersInput";
import { SupportTicketUpdateManyWithoutUsersInput } from "./SupportTicketUpdateManyWithoutUsersInput";
import { TransactionUpdateManyWithoutUsersInput } from "./TransactionUpdateManyWithoutUsersInput";
import { EmployeeWhereUniqueInput } from "../../employee/base/EmployeeWhereUniqueInput";
import { ExpenseUpdateManyWithoutUsersInput } from "./ExpenseUpdateManyWithoutUsersInput";
import { InvoiceUpdateManyWithoutUsersInput } from "./InvoiceUpdateManyWithoutUsersInput";
import { MarketingLeadUpdateManyWithoutUsersInput } from "./MarketingLeadUpdateManyWithoutUsersInput";
import { UserPermissionUpdateManyWithoutUsersInput } from "./UserPermissionUpdateManyWithoutUsersInput";
import { PopRechargeUpdateManyWithoutUsersInput } from "./PopRechargeUpdateManyWithoutUsersInput";
import { ResellerWhereUniqueInput } from "../../reseller/base/ResellerWhereUniqueInput";
import { EnumUserRoles } from "./EnumUserRoles";
import { SessionUpdateManyWithoutUsersInput } from "./SessionUpdateManyWithoutUsersInput";
import { SubscriptionUpdateManyWithoutUsersInput } from "./SubscriptionUpdateManyWithoutUsersInput";
import { TokenUpdateManyWithoutUsersInput } from "./TokenUpdateManyWithoutUsersInput";
import { UsageUpdateManyWithoutUsersInput } from "./UsageUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AccountUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AccountUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AccountUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  accounts?: AccountUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => ActivityLogUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ActivityLogUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ActivityLogUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  activityLogs?: ActivityLogUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => SupportTicketUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SupportTicketUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SupportTicketUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  assignedTickets?: SupportTicketUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => TransactionUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TransactionUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TransactionUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  collectedBills?: TransactionUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  emailVerified?: Date | null;

  @ApiProperty({
    required: false,
    type: () => EmployeeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => EmployeeWhereUniqueInput)
  @IsOptional()
  @Field(() => EmployeeWhereUniqueInput, {
    nullable: true,
  })
  employeeProfile?: EmployeeWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ExpenseUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ExpenseUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ExpenseUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  expenses?: ExpenseUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  image?: string | null;

  @ApiProperty({
    required: false,
    type: () => InvoiceUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => InvoiceUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => InvoiceUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  invoices?: InvoiceUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isActive?: boolean;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => MarketingLeadUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => MarketingLeadUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => MarketingLeadUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  marketingLeads?: MarketingLeadUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserPermissionUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserPermissionUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserPermissionUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  permissions?: UserPermissionUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;

  @ApiProperty({
    required: false,
    type: () => PopRechargeUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => PopRechargeUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => PopRechargeUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  popRecharges?: PopRechargeUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => ResellerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ResellerWhereUniqueInput)
  @IsOptional()
  @Field(() => ResellerWhereUniqueInput, {
    nullable: true,
  })
  resellerProfile?: ResellerWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    enum: EnumUserRoles,
  })
  @IsEnum(EnumUserRoles)
  @IsOptional()
  @Field(() => EnumUserRoles, {
    nullable: true,
  })
  roles?:
    | "USER"
    | "ADMIN"
    | "SUPER_ADMIN"
    | "MANAGER"
    | "ACCOUNTANT"
    | "SUPPORT"
    | "CABLE_TEAM"
    | "BILL_MAN"
    | "MARKETING_AGENT"
    | "RESELLER"
    | "SUB_RESELLER";

  @ApiProperty({
    required: false,
    type: () => SessionUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SessionUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SessionUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  sessions?: SessionUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => SubscriptionUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SubscriptionUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SubscriptionUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  subscriptions?: SubscriptionUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => TokenUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TokenUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TokenUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  supportTickets?: TokenUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => SupportTicketUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SupportTicketUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SupportTicketUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  tickets?: SupportTicketUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => UsageUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UsageUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UsageUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  usages?: UsageUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string | null;
}

export { UserUpdateInput as UserUpdateInput };
