/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TicketCategoryService } from "../ticketCategory.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TicketCategoryCreateInput } from "./TicketCategoryCreateInput";
import { TicketCategory } from "./TicketCategory";
import { TicketCategoryFindManyArgs } from "./TicketCategoryFindManyArgs";
import { TicketCategoryWhereUniqueInput } from "./TicketCategoryWhereUniqueInput";
import { TicketCategoryUpdateInput } from "./TicketCategoryUpdateInput";
import { SupportTicketFindManyArgs } from "../../supportTicket/base/SupportTicketFindManyArgs";
import { SupportTicket } from "../../supportTicket/base/SupportTicket";
import { SupportTicketWhereUniqueInput } from "../../supportTicket/base/SupportTicketWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TicketCategoryControllerBase {
  constructor(
    protected readonly service: TicketCategoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TicketCategory })
  @swagger.ApiBody({
    type: TicketCategoryCreateInput,
  })
  @nestAccessControl.UseRoles({
    resource: "TicketCategory",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTicketCategory(
    @common.Body() data: TicketCategoryCreateInput
  ): Promise<TicketCategory> {
    return await this.service.createTicketCategory({
      data: data,
      select: {
        createdAt: true,
        id: true,
        price: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [TicketCategory] })
  @ApiNestedQuery(TicketCategoryFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TicketCategory",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ticketCategories(
    @common.Req() request: Request
  ): Promise<TicketCategory[]> {
    const args = plainToClass(TicketCategoryFindManyArgs, request.query);
    return this.service.ticketCategories({
      ...args,
      select: {
        createdAt: true,
        id: true,
        price: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TicketCategory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TicketCategory",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ticketCategory(
    @common.Param() params: TicketCategoryWhereUniqueInput
  ): Promise<TicketCategory | null> {
    const result = await this.service.ticketCategory({
      where: params,
      select: {
        createdAt: true,
        id: true,
        price: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TicketCategory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiBody({
    type: TicketCategoryUpdateInput,
  })
  @nestAccessControl.UseRoles({
    resource: "TicketCategory",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTicketCategory(
    @common.Param() params: TicketCategoryWhereUniqueInput,
    @common.Body() data: TicketCategoryUpdateInput
  ): Promise<TicketCategory | null> {
    try {
      return await this.service.updateTicketCategory({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          price: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TicketCategory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TicketCategory",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTicketCategory(
    @common.Param() params: TicketCategoryWhereUniqueInput
  ): Promise<TicketCategory | null> {
    try {
      return await this.service.deleteTicketCategory({
        where: params,
        select: {
          createdAt: true,
          id: true,
          price: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/tickets")
  @ApiNestedQuery(SupportTicketFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SupportTicket",
    action: "read",
    possession: "any",
  })
  async findTickets(
    @common.Req() request: Request,
    @common.Param() params: TicketCategoryWhereUniqueInput
  ): Promise<SupportTicket[]> {
    const query = plainToClass(SupportTicketFindManyArgs, request.query);
    const results = await this.service.findTickets(params.id, {
      ...query,
      select: {
        assignee: {
          select: {
            id: true,
          },
        },

        category: {
          select: {
            id: true,
          },
        },

        closedAt: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        description: true,
        id: true,
        priority: true,
        resolvedAt: true,
        status: true,
        subject: true,
        ticketNo: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/tickets")
  @nestAccessControl.UseRoles({
    resource: "TicketCategory",
    action: "update",
    possession: "any",
  })
  async connectTickets(
    @common.Param() params: TicketCategoryWhereUniqueInput,
    @common.Body() body: SupportTicketWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tickets: {
        connect: body,
      },
    };
    await this.service.updateTicketCategory({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/tickets")
  @nestAccessControl.UseRoles({
    resource: "TicketCategory",
    action: "update",
    possession: "any",
  })
  async updateTickets(
    @common.Param() params: TicketCategoryWhereUniqueInput,
    @common.Body() body: SupportTicketWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tickets: {
        set: body,
      },
    };
    await this.service.updateTicketCategory({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/tickets")
  @nestAccessControl.UseRoles({
    resource: "TicketCategory",
    action: "update",
    possession: "any",
  })
  async disconnectTickets(
    @common.Param() params: TicketCategoryWhereUniqueInput,
    @common.Body() body: SupportTicketWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tickets: {
        disconnect: body,
      },
    };
    await this.service.updateTicketCategory({
      where: params,
      data,
      select: { id: true },
    });
  }
}
