/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { MarketingLead } from "./MarketingLead";
import { MarketingLeadCountArgs } from "./MarketingLeadCountArgs";
import { MarketingLeadFindManyArgs } from "./MarketingLeadFindManyArgs";
import { MarketingLeadFindUniqueArgs } from "./MarketingLeadFindUniqueArgs";
import { CreateMarketingLeadArgs } from "./CreateMarketingLeadArgs";
import { UpdateMarketingLeadArgs } from "./UpdateMarketingLeadArgs";
import { DeleteMarketingLeadArgs } from "./DeleteMarketingLeadArgs";
import { User } from "../../user/base/User";
import { MarketingLeadService } from "../marketingLead.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => MarketingLead)
export class MarketingLeadResolverBase {
  constructor(
    protected readonly service: MarketingLeadService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "MarketingLead",
    action: "read",
    possession: "any",
  })
  async _marketingLeadsMeta(
    @graphql.Args() args: MarketingLeadCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [MarketingLead])
  @nestAccessControl.UseRoles({
    resource: "MarketingLead",
    action: "read",
    possession: "any",
  })
  async marketingLeads(
    @graphql.Args() args: MarketingLeadFindManyArgs
  ): Promise<MarketingLead[]> {
    return this.service.marketingLeads(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => MarketingLead, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "MarketingLead",
    action: "read",
    possession: "own",
  })
  async marketingLead(
    @graphql.Args() args: MarketingLeadFindUniqueArgs
  ): Promise<MarketingLead | null> {
    const result = await this.service.marketingLead(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => MarketingLead)
  @nestAccessControl.UseRoles({
    resource: "MarketingLead",
    action: "create",
    possession: "any",
  })
  async createMarketingLead(
    @graphql.Args() args: CreateMarketingLeadArgs
  ): Promise<MarketingLead> {
    return await this.service.createMarketingLead({
      ...args,
      data: {
        ...args.data,

        agent: {
          connect: args.data.agent,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => MarketingLead)
  @nestAccessControl.UseRoles({
    resource: "MarketingLead",
    action: "update",
    possession: "any",
  })
  async updateMarketingLead(
    @graphql.Args() args: UpdateMarketingLeadArgs
  ): Promise<MarketingLead | null> {
    try {
      return await this.service.updateMarketingLead({
        ...args,
        data: {
          ...args.data,

          agent: {
            connect: args.data.agent,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => MarketingLead)
  @nestAccessControl.UseRoles({
    resource: "MarketingLead",
    action: "delete",
    possession: "any",
  })
  async deleteMarketingLead(
    @graphql.Args() args: DeleteMarketingLeadArgs
  ): Promise<MarketingLead | null> {
    try {
      return await this.service.deleteMarketingLead(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "agent",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getAgent(
    @graphql.Parent() parent: MarketingLead
  ): Promise<User | null> {
    const result = await this.service.getAgent(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
