/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  MarketingLead as PrismaMarketingLead,
  User as PrismaUser,
} from "@prisma/client";

export class MarketingLeadServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.MarketingLeadCountArgs, "select">
  ): Promise<number> {
    return this.prisma.marketingLead.count(args);
  }

  async marketingLeads(
    args: Prisma.MarketingLeadFindManyArgs
  ): Promise<PrismaMarketingLead[]> {
    return this.prisma.marketingLead.findMany(args);
  }
  async marketingLead(
    args: Prisma.MarketingLeadFindUniqueArgs
  ): Promise<PrismaMarketingLead | null> {
    return this.prisma.marketingLead.findUnique(args);
  }
  async createMarketingLead(
    args: Prisma.MarketingLeadCreateArgs
  ): Promise<PrismaMarketingLead> {
    return this.prisma.marketingLead.create(args);
  }
  async updateMarketingLead(
    args: Prisma.MarketingLeadUpdateArgs
  ): Promise<PrismaMarketingLead> {
    return this.prisma.marketingLead.update(args);
  }
  async deleteMarketingLead(
    args: Prisma.MarketingLeadDeleteArgs
  ): Promise<PrismaMarketingLead> {
    return this.prisma.marketingLead.delete(args);
  }

  async getAgent(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.marketingLead
      .findUnique({
        where: { id: parentId },
      })
      .agent();
  }
}
