/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  UserPermission as PrismaUserPermission,
  Permission as PrismaPermission,
  User as PrismaUser,
} from "@prisma/client";

export class UserPermissionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.UserPermissionCountArgs, "select">
  ): Promise<number> {
    return this.prisma.userPermission.count(args);
  }

  async userPermissions(
    args: Prisma.UserPermissionFindManyArgs
  ): Promise<PrismaUserPermission[]> {
    return this.prisma.userPermission.findMany(args);
  }
  async userPermission(
    args: Prisma.UserPermissionFindUniqueArgs
  ): Promise<PrismaUserPermission | null> {
    return this.prisma.userPermission.findUnique(args);
  }
  async createUserPermission(
    args: Prisma.UserPermissionCreateArgs
  ): Promise<PrismaUserPermission> {
    return this.prisma.userPermission.create(args);
  }
  async updateUserPermission(
    args: Prisma.UserPermissionUpdateArgs
  ): Promise<PrismaUserPermission> {
    return this.prisma.userPermission.update(args);
  }
  async deleteUserPermission(
    args: Prisma.UserPermissionDeleteArgs
  ): Promise<PrismaUserPermission> {
    return this.prisma.userPermission.delete(args);
  }

  async getPermission(parentId: string): Promise<PrismaPermission | null> {
    return this.prisma.userPermission
      .findUnique({
        where: { id: parentId },
      })
      .permission();
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.userPermission
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
