import { StringNullableFilter } from "../../util/StringNullableFilter";
import { AreaWhereUniqueInput } from "../area/AreaWhereUniqueInput";
import { DecimalFilter } from "../../util/DecimalFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { CustomerListRelationFilter } from "../customer/CustomerListRelationFilter";
import { ExpenseListRelationFilter } from "../expense/ExpenseListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { PopWhereUniqueInput } from "./PopWhereUniqueInput";
import { ProductItemListRelationFilter } from "../productItem/ProductItemListRelationFilter";
import { PopRechargeListRelationFilter } from "../popRecharge/PopRechargeListRelationFilter";
import { ResellerWhereUniqueInput } from "../reseller/ResellerWhereUniqueInput";
import { MikroTikRouterListRelationFilter } from "../mikroTikRouter/MikroTikRouterListRelationFilter";
import { PopListRelationFilter } from "./PopListRelationFilter";

export type PopWhereInput = {
  address?: StringNullableFilter;
  area?: AreaWhereUniqueInput;
  balance?: DecimalFilter;
  createdAt?: DateTimeFilter;
  customers?: CustomerListRelationFilter;
  expenses?: ExpenseListRelationFilter;
  id?: StringFilter;
  name?: StringFilter;
  parentPop?: PopWhereUniqueInput;
  products?: ProductItemListRelationFilter;
  rechargeHistory?: PopRechargeListRelationFilter;
  reseller?: ResellerWhereUniqueInput;
  routers?: MikroTikRouterListRelationFilter;
  subPops?: PopListRelationFilter;
  type?: "MAIN" | "RESELLER" | "SUB_POP";
  updatedAt?: DateTimeFilter;
};
