/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field, Float } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsNumber,
  Max,
} from "class-validator";
import { Type } from "class-transformer";
import { PurchaseItem } from "../../purchaseItem/base/PurchaseItem";
import { ProductItem } from "../../productItem/base/ProductItem";
import { Supplier } from "../../supplier/base/Supplier";
import { Decimal } from "decimal.js";

@ObjectType()
class Purchase {
  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  date!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  invoiceNo!: string | null;

  @ApiProperty({
    required: false,
    type: () => [PurchaseItem],
  })
  @ValidateNested()
  @Type(() => PurchaseItem)
  @IsOptional()
  items?: Array<PurchaseItem>;

  @ApiProperty({
    required: false,
    type: () => [ProductItem],
  })
  @ValidateNested()
  @Type(() => ProductItem)
  @IsOptional()
  stockItems?: Array<ProductItem>;

  @ApiProperty({
    required: true,
    type: () => Supplier,
  })
  @ValidateNested()
  @Type(() => Supplier)
  supplier?: Supplier;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @Field(() => Float)
  totalAmount!: Decimal;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Purchase as Purchase };
