/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PurchaseItemService } from "../purchaseItem.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PurchaseItemCreateInput } from "./PurchaseItemCreateInput";
import { PurchaseItem } from "./PurchaseItem";
import { PurchaseItemFindManyArgs } from "./PurchaseItemFindManyArgs";
import { PurchaseItemWhereUniqueInput } from "./PurchaseItemWhereUniqueInput";
import { PurchaseItemUpdateInput } from "./PurchaseItemUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PurchaseItemControllerBase {
  constructor(
    protected readonly service: PurchaseItemService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PurchaseItem })
  @swagger.ApiBody({
    type: PurchaseItemCreateInput,
  })
  @nestAccessControl.UseRoles({
    resource: "PurchaseItem",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPurchaseItem(
    @common.Body() data: PurchaseItemCreateInput
  ): Promise<PurchaseItem> {
    return await this.service.createPurchaseItem({
      data: {
        ...data,

        product: {
          connect: data.product,
        },

        purchase: {
          connect: data.purchase,
        },
      },
      select: {
        id: true,

        product: {
          select: {
            id: true,
          },
        },

        purchase: {
          select: {
            id: true,
          },
        },

        quantity: true,
        unitPrice: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PurchaseItem] })
  @ApiNestedQuery(PurchaseItemFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PurchaseItem",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async purchaseItems(@common.Req() request: Request): Promise<PurchaseItem[]> {
    const args = plainToClass(PurchaseItemFindManyArgs, request.query);
    return this.service.purchaseItems({
      ...args,
      select: {
        id: true,

        product: {
          select: {
            id: true,
          },
        },

        purchase: {
          select: {
            id: true,
          },
        },

        quantity: true,
        unitPrice: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PurchaseItem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PurchaseItem",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async purchaseItem(
    @common.Param() params: PurchaseItemWhereUniqueInput
  ): Promise<PurchaseItem | null> {
    const result = await this.service.purchaseItem({
      where: params,
      select: {
        id: true,

        product: {
          select: {
            id: true,
          },
        },

        purchase: {
          select: {
            id: true,
          },
        },

        quantity: true,
        unitPrice: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PurchaseItem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiBody({
    type: PurchaseItemUpdateInput,
  })
  @nestAccessControl.UseRoles({
    resource: "PurchaseItem",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePurchaseItem(
    @common.Param() params: PurchaseItemWhereUniqueInput,
    @common.Body() data: PurchaseItemUpdateInput
  ): Promise<PurchaseItem | null> {
    try {
      return await this.service.updatePurchaseItem({
        where: params,
        data: {
          ...data,

          product: {
            connect: data.product,
          },

          purchase: {
            connect: data.purchase,
          },
        },
        select: {
          id: true,

          product: {
            select: {
              id: true,
            },
          },

          purchase: {
            select: {
              id: true,
            },
          },

          quantity: true,
          unitPrice: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PurchaseItem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PurchaseItem",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePurchaseItem(
    @common.Param() params: PurchaseItemWhereUniqueInput
  ): Promise<PurchaseItem | null> {
    try {
      return await this.service.deletePurchaseItem({
        where: params,
        select: {
          id: true,

          product: {
            select: {
              id: true,
            },
          },

          purchase: {
            select: {
              id: true,
            },
          },

          quantity: true,
          unitPrice: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
