/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { BillSheet } from "./BillSheet";
import { BillSheetCountArgs } from "./BillSheetCountArgs";
import { BillSheetFindManyArgs } from "./BillSheetFindManyArgs";
import { BillSheetFindUniqueArgs } from "./BillSheetFindUniqueArgs";
import { CreateBillSheetArgs } from "./CreateBillSheetArgs";
import { UpdateBillSheetArgs } from "./UpdateBillSheetArgs";
import { DeleteBillSheetArgs } from "./DeleteBillSheetArgs";
import { Customer } from "../../customer/base/Customer";
import { BillSheetService } from "../billSheet.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => BillSheet)
export class BillSheetResolverBase {
  constructor(
    protected readonly service: BillSheetService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "BillSheet",
    action: "read",
    possession: "any",
  })
  async _billSheetsMeta(
    @graphql.Args() args: BillSheetCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [BillSheet])
  @nestAccessControl.UseRoles({
    resource: "BillSheet",
    action: "read",
    possession: "any",
  })
  async billSheets(
    @graphql.Args() args: BillSheetFindManyArgs
  ): Promise<BillSheet[]> {
    return this.service.billSheets(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => BillSheet, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "BillSheet",
    action: "read",
    possession: "own",
  })
  async billSheet(
    @graphql.Args() args: BillSheetFindUniqueArgs
  ): Promise<BillSheet | null> {
    const result = await this.service.billSheet(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => BillSheet)
  @nestAccessControl.UseRoles({
    resource: "BillSheet",
    action: "create",
    possession: "any",
  })
  async createBillSheet(
    @graphql.Args() args: CreateBillSheetArgs
  ): Promise<BillSheet> {
    return await this.service.createBillSheet({
      ...args,
      data: {
        ...args.data,

        customer: {
          connect: args.data.customer,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => BillSheet)
  @nestAccessControl.UseRoles({
    resource: "BillSheet",
    action: "update",
    possession: "any",
  })
  async updateBillSheet(
    @graphql.Args() args: UpdateBillSheetArgs
  ): Promise<BillSheet | null> {
    try {
      return await this.service.updateBillSheet({
        ...args,
        data: {
          ...args.data,

          customer: {
            connect: args.data.customer,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => BillSheet)
  @nestAccessControl.UseRoles({
    resource: "BillSheet",
    action: "delete",
    possession: "any",
  })
  async deleteBillSheet(
    @graphql.Args() args: DeleteBillSheetArgs
  ): Promise<BillSheet | null> {
    try {
      return await this.service.deleteBillSheet(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Customer, {
    nullable: true,
    name: "customer",
  })
  @nestAccessControl.UseRoles({
    resource: "Customer",
    action: "read",
    possession: "any",
  })
  async getCustomer(
    @graphql.Parent() parent: BillSheet
  ): Promise<Customer | null> {
    const result = await this.service.getCustomer(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
