/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  BillSheet as PrismaBillSheet,
  Customer as PrismaCustomer,
} from "@prisma/client";

export class BillSheetServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.BillSheetCountArgs, "select">
  ): Promise<number> {
    return this.prisma.billSheet.count(args);
  }

  async billSheets(
    args: Prisma.BillSheetFindManyArgs
  ): Promise<PrismaBillSheet[]> {
    return this.prisma.billSheet.findMany(args);
  }
  async billSheet(
    args: Prisma.BillSheetFindUniqueArgs
  ): Promise<PrismaBillSheet | null> {
    return this.prisma.billSheet.findUnique(args);
  }
  async createBillSheet(
    args: Prisma.BillSheetCreateArgs
  ): Promise<PrismaBillSheet> {
    return this.prisma.billSheet.create(args);
  }
  async updateBillSheet(
    args: Prisma.BillSheetUpdateArgs
  ): Promise<PrismaBillSheet> {
    return this.prisma.billSheet.update(args);
  }
  async deleteBillSheet(
    args: Prisma.BillSheetDeleteArgs
  ): Promise<PrismaBillSheet> {
    return this.prisma.billSheet.delete(args);
  }

  async getCustomer(parentId: string): Promise<PrismaCustomer | null> {
    return this.prisma.billSheet
      .findUnique({
        where: { id: parentId },
      })
      .customer();
  }
}
