/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { BillSheetService } from "../billSheet.service";
import { BillSheetCreateInput } from "./BillSheetCreateInput";
import { BillSheet } from "./BillSheet";
import { BillSheetFindManyArgs } from "./BillSheetFindManyArgs";
import { BillSheetWhereUniqueInput } from "./BillSheetWhereUniqueInput";
import { BillSheetUpdateInput } from "./BillSheetUpdateInput";

export class BillSheetControllerBase {
  constructor(protected readonly service: BillSheetService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: BillSheet })
  @swagger.ApiBody({
    type: BillSheetCreateInput,
  })
  async createBillSheet(
    @common.Body() data: BillSheetCreateInput
  ): Promise<BillSheet> {
    return await this.service.createBillSheet({
      data: {
        ...data,

        customer: {
          connect: data.customer,
        },
      },
      select: {
        customer: {
          select: {
            id: true,
          },
        },

        generatedAt: true,
        id: true,
        month: true,
        payable: true,
        status: true,
        year: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [BillSheet] })
  @ApiNestedQuery(BillSheetFindManyArgs)
  async billSheets(@common.Req() request: Request): Promise<BillSheet[]> {
    const args = plainToClass(BillSheetFindManyArgs, request.query);
    return this.service.billSheets({
      ...args,
      select: {
        customer: {
          select: {
            id: true,
          },
        },

        generatedAt: true,
        id: true,
        month: true,
        payable: true,
        status: true,
        year: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: BillSheet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async billSheet(
    @common.Param() params: BillSheetWhereUniqueInput
  ): Promise<BillSheet | null> {
    const result = await this.service.billSheet({
      where: params,
      select: {
        customer: {
          select: {
            id: true,
          },
        },

        generatedAt: true,
        id: true,
        month: true,
        payable: true,
        status: true,
        year: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: BillSheet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiBody({
    type: BillSheetUpdateInput,
  })
  async updateBillSheet(
    @common.Param() params: BillSheetWhereUniqueInput,
    @common.Body() data: BillSheetUpdateInput
  ): Promise<BillSheet | null> {
    try {
      return await this.service.updateBillSheet({
        where: params,
        data: {
          ...data,

          customer: {
            connect: data.customer,
          },
        },
        select: {
          customer: {
            select: {
              id: true,
            },
          },

          generatedAt: true,
          id: true,
          month: true,
          payable: true,
          status: true,
          year: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: BillSheet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteBillSheet(
    @common.Param() params: BillSheetWhereUniqueInput
  ): Promise<BillSheet | null> {
    try {
      return await this.service.deleteBillSheet({
        where: params,
        select: {
          customer: {
            select: {
              id: true,
            },
          },

          generatedAt: true,
          id: true,
          month: true,
          payable: true,
          status: true,
          year: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
