/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CustomerSession } from "./CustomerSession";
import { CustomerSessionCountArgs } from "./CustomerSessionCountArgs";
import { CustomerSessionFindManyArgs } from "./CustomerSessionFindManyArgs";
import { CustomerSessionFindUniqueArgs } from "./CustomerSessionFindUniqueArgs";
import { CreateCustomerSessionArgs } from "./CreateCustomerSessionArgs";
import { UpdateCustomerSessionArgs } from "./UpdateCustomerSessionArgs";
import { DeleteCustomerSessionArgs } from "./DeleteCustomerSessionArgs";
import { Customer } from "../../customer/base/Customer";
import { CustomerSessionService } from "../customerSession.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => CustomerSession)
export class CustomerSessionResolverBase {
  constructor(
    protected readonly service: CustomerSessionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "CustomerSession",
    action: "read",
    possession: "any",
  })
  async _customerSessionsMeta(
    @graphql.Args() args: CustomerSessionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [CustomerSession])
  @nestAccessControl.UseRoles({
    resource: "CustomerSession",
    action: "read",
    possession: "any",
  })
  async customerSessions(
    @graphql.Args() args: CustomerSessionFindManyArgs
  ): Promise<CustomerSession[]> {
    return this.service.customerSessions(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => CustomerSession, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CustomerSession",
    action: "read",
    possession: "own",
  })
  async customerSession(
    @graphql.Args() args: CustomerSessionFindUniqueArgs
  ): Promise<CustomerSession | null> {
    const result = await this.service.customerSession(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => CustomerSession)
  @nestAccessControl.UseRoles({
    resource: "CustomerSession",
    action: "create",
    possession: "any",
  })
  async createCustomerSession(
    @graphql.Args() args: CreateCustomerSessionArgs
  ): Promise<CustomerSession> {
    return await this.service.createCustomerSession({
      ...args,
      data: {
        ...args.data,

        customer: {
          connect: args.data.customer,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => CustomerSession)
  @nestAccessControl.UseRoles({
    resource: "CustomerSession",
    action: "update",
    possession: "any",
  })
  async updateCustomerSession(
    @graphql.Args() args: UpdateCustomerSessionArgs
  ): Promise<CustomerSession | null> {
    try {
      return await this.service.updateCustomerSession({
        ...args,
        data: {
          ...args.data,

          customer: {
            connect: args.data.customer,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CustomerSession)
  @nestAccessControl.UseRoles({
    resource: "CustomerSession",
    action: "delete",
    possession: "any",
  })
  async deleteCustomerSession(
    @graphql.Args() args: DeleteCustomerSessionArgs
  ): Promise<CustomerSession | null> {
    try {
      return await this.service.deleteCustomerSession(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Customer, {
    nullable: true,
    name: "customer",
  })
  @nestAccessControl.UseRoles({
    resource: "Customer",
    action: "read",
    possession: "any",
  })
  async getCustomer(
    @graphql.Parent() parent: CustomerSession
  ): Promise<Customer | null> {
    const result = await this.service.getCustomer(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
