/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PackageModelService } from "../packageModel.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PackageModelCreateInput } from "./PackageModelCreateInput";
import { PackageModel } from "./PackageModel";
import { PackageModelFindManyArgs } from "./PackageModelFindManyArgs";
import { PackageModelWhereUniqueInput } from "./PackageModelWhereUniqueInput";
import { PackageModelUpdateInput } from "./PackageModelUpdateInput";
import { CustomerFindManyArgs } from "../../customer/base/CustomerFindManyArgs";
import { Customer } from "../../customer/base/Customer";
import { CustomerWhereUniqueInput } from "../../customer/base/CustomerWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PackageModelControllerBase {
  constructor(
    protected readonly service: PackageModelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PackageModel })
  @swagger.ApiBody({
    type: PackageModelCreateInput,
  })
  @nestAccessControl.UseRoles({
    resource: "PackageModel",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPackageModel(
    @common.Body() data: PackageModelCreateInput
  ): Promise<PackageModel> {
    return await this.service.createPackageModel({
      data: data,
      select: {
        id: true,
        mikroTikProfile: true,
        name: true,
        price: true,
        speed: true,
        type: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PackageModel] })
  @ApiNestedQuery(PackageModelFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PackageModel",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async packageModels(@common.Req() request: Request): Promise<PackageModel[]> {
    const args = plainToClass(PackageModelFindManyArgs, request.query);
    return this.service.packageModels({
      ...args,
      select: {
        id: true,
        mikroTikProfile: true,
        name: true,
        price: true,
        speed: true,
        type: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PackageModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PackageModel",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async packageModel(
    @common.Param() params: PackageModelWhereUniqueInput
  ): Promise<PackageModel | null> {
    const result = await this.service.packageModel({
      where: params,
      select: {
        id: true,
        mikroTikProfile: true,
        name: true,
        price: true,
        speed: true,
        type: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PackageModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiBody({
    type: PackageModelUpdateInput,
  })
  @nestAccessControl.UseRoles({
    resource: "PackageModel",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePackageModel(
    @common.Param() params: PackageModelWhereUniqueInput,
    @common.Body() data: PackageModelUpdateInput
  ): Promise<PackageModel | null> {
    try {
      return await this.service.updatePackageModel({
        where: params,
        data: data,
        select: {
          id: true,
          mikroTikProfile: true,
          name: true,
          price: true,
          speed: true,
          type: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PackageModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PackageModel",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePackageModel(
    @common.Param() params: PackageModelWhereUniqueInput
  ): Promise<PackageModel | null> {
    try {
      return await this.service.deletePackageModel({
        where: params,
        select: {
          id: true,
          mikroTikProfile: true,
          name: true,
          price: true,
          speed: true,
          type: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/customers")
  @ApiNestedQuery(CustomerFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Customer",
    action: "read",
    possession: "any",
  })
  async findCustomers(
    @common.Req() request: Request,
    @common.Param() params: PackageModelWhereUniqueInput
  ): Promise<Customer[]> {
    const query = plainToClass(CustomerFindManyArgs, request.query);
    const results = await this.service.findCustomers(params.id, {
      ...query,
      select: {
        address: true,

        area: {
          select: {
            id: true,
          },
        },

        balance: true,
        billingCycle: true,
        connectionDate: true,
        createdAt: true,
        customerId: true,
        dueAmount: true,
        email: true,
        id: true,
        ipAddress: true,
        macAddress: true,
        monthlyBill: true,
        name: true,
        nid: true,
        onuMac: true,

        packageField: {
          select: {
            id: true,
          },
        },

        phone: true,

        pop: {
          select: {
            id: true,
          },
        },

        pppoePassword: true,
        pppoeUsername: true,
        status: true,
        tempExtensionActive: true,
        tempExtensionExpiresAt: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/customers")
  @nestAccessControl.UseRoles({
    resource: "PackageModel",
    action: "update",
    possession: "any",
  })
  async connectCustomers(
    @common.Param() params: PackageModelWhereUniqueInput,
    @common.Body() body: CustomerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      customers: {
        connect: body,
      },
    };
    await this.service.updatePackageModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/customers")
  @nestAccessControl.UseRoles({
    resource: "PackageModel",
    action: "update",
    possession: "any",
  })
  async updateCustomers(
    @common.Param() params: PackageModelWhereUniqueInput,
    @common.Body() body: CustomerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      customers: {
        set: body,
      },
    };
    await this.service.updatePackageModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/customers")
  @nestAccessControl.UseRoles({
    resource: "PackageModel",
    action: "update",
    possession: "any",
  })
  async disconnectCustomers(
    @common.Param() params: PackageModelWhereUniqueInput,
    @common.Body() body: CustomerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      customers: {
        disconnect: body,
      },
    };
    await this.service.updatePackageModel({
      where: params,
      data,
      select: { id: true },
    });
  }
}
