/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  PopRecharge as PrismaPopRecharge,
  User as PrismaUser,
  Pop as PrismaPop,
} from "@prisma/client";

export class PopRechargeServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.PopRechargeCountArgs, "select">
  ): Promise<number> {
    return this.prisma.popRecharge.count(args);
  }

  async popRecharges(
    args: Prisma.PopRechargeFindManyArgs
  ): Promise<PrismaPopRecharge[]> {
    return this.prisma.popRecharge.findMany(args);
  }
  async popRecharge(
    args: Prisma.PopRechargeFindUniqueArgs
  ): Promise<PrismaPopRecharge | null> {
    return this.prisma.popRecharge.findUnique(args);
  }
  async createPopRecharge(
    args: Prisma.PopRechargeCreateArgs
  ): Promise<PrismaPopRecharge> {
    return this.prisma.popRecharge.create(args);
  }
  async updatePopRecharge(
    args: Prisma.PopRechargeUpdateArgs
  ): Promise<PrismaPopRecharge> {
    return this.prisma.popRecharge.update(args);
  }
  async deletePopRecharge(
    args: Prisma.PopRechargeDeleteArgs
  ): Promise<PrismaPopRecharge> {
    return this.prisma.popRecharge.delete(args);
  }

  async getPerformedByUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.popRecharge
      .findUnique({
        where: { id: parentId },
      })
      .performedByUser();
  }

  async getPop(parentId: string): Promise<PrismaPop | null> {
    return this.prisma.popRecharge
      .findUnique({
        where: { id: parentId },
      })
      .pop();
  }
}
