/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PopRecharge } from "./PopRecharge";
import { PopRechargeCountArgs } from "./PopRechargeCountArgs";
import { PopRechargeFindManyArgs } from "./PopRechargeFindManyArgs";
import { PopRechargeFindUniqueArgs } from "./PopRechargeFindUniqueArgs";
import { CreatePopRechargeArgs } from "./CreatePopRechargeArgs";
import { UpdatePopRechargeArgs } from "./UpdatePopRechargeArgs";
import { DeletePopRechargeArgs } from "./DeletePopRechargeArgs";
import { Pop } from "../../pop/base/Pop";
import { PopRechargeService } from "../popRecharge.service";
@graphql.Resolver(() => PopRecharge)
export class PopRechargeResolverBase {
  constructor(protected readonly service: PopRechargeService) {}

  async _popRechargesMeta(
    @graphql.Args() args: PopRechargeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [PopRecharge])
  async popRecharges(
    @graphql.Args() args: PopRechargeFindManyArgs
  ): Promise<PopRecharge[]> {
    return this.service.popRecharges(args);
  }

  @graphql.Query(() => PopRecharge, { nullable: true })
  async popRecharge(
    @graphql.Args() args: PopRechargeFindUniqueArgs
  ): Promise<PopRecharge | null> {
    const result = await this.service.popRecharge(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PopRecharge)
  async createPopRecharge(
    @graphql.Args() args: CreatePopRechargeArgs
  ): Promise<PopRecharge> {
    return await this.service.createPopRecharge({
      ...args,
      data: {
        ...args.data,

        pop: {
          connect: args.data.pop,
        },
      },
    });
  }

  @graphql.Mutation(() => PopRecharge)
  async updatePopRecharge(
    @graphql.Args() args: UpdatePopRechargeArgs
  ): Promise<PopRecharge | null> {
    try {
      return await this.service.updatePopRecharge({
        ...args,
        data: {
          ...args.data,

          pop: {
            connect: args.data.pop,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PopRecharge)
  async deletePopRecharge(
    @graphql.Args() args: DeletePopRechargeArgs
  ): Promise<PopRecharge | null> {
    try {
      return await this.service.deletePopRecharge(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Pop, {
    nullable: true,
    name: "pop",
  })
  async getPop(@graphql.Parent() parent: PopRecharge): Promise<Pop | null> {
    const result = await this.service.getPop(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
