/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Pop } from "./Pop";
import { PopCountArgs } from "./PopCountArgs";
import { PopFindManyArgs } from "./PopFindManyArgs";
import { PopFindUniqueArgs } from "./PopFindUniqueArgs";
import { CreatePopArgs } from "./CreatePopArgs";
import { UpdatePopArgs } from "./UpdatePopArgs";
import { DeletePopArgs } from "./DeletePopArgs";
import { CustomerFindManyArgs } from "../../customer/base/CustomerFindManyArgs";
import { Customer } from "../../customer/base/Customer";
import { ExpenseFindManyArgs } from "../../expense/base/ExpenseFindManyArgs";
import { Expense } from "../../expense/base/Expense";
import { ProductItemFindManyArgs } from "../../productItem/base/ProductItemFindManyArgs";
import { ProductItem } from "../../productItem/base/ProductItem";
import { PopRechargeFindManyArgs } from "../../popRecharge/base/PopRechargeFindManyArgs";
import { PopRecharge } from "../../popRecharge/base/PopRecharge";
import { Area } from "../../area/base/Area";
import { Reseller } from "../../reseller/base/Reseller";
import { PopService } from "../pop.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Pop)
export class PopResolverBase {
  constructor(
    protected readonly service: PopService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Pop",
    action: "read",
    possession: "any",
  })
  async _popsMeta(
    @graphql.Args() args: PopCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Pop])
  @nestAccessControl.UseRoles({
    resource: "Pop",
    action: "read",
    possession: "any",
  })
  async pops(@graphql.Args() args: PopFindManyArgs): Promise<Pop[]> {
    return this.service.pops(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Pop, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Pop",
    action: "read",
    possession: "own",
  })
  async pop(@graphql.Args() args: PopFindUniqueArgs): Promise<Pop | null> {
    const result = await this.service.pop(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Pop)
  @nestAccessControl.UseRoles({
    resource: "Pop",
    action: "create",
    possession: "any",
  })
  async createPop(@graphql.Args() args: CreatePopArgs): Promise<Pop> {
    return await this.service.createPop({
      ...args,
      data: {
        ...args.data,

        area: args.data.area
          ? {
              connect: args.data.area,
            }
          : undefined,

        parentPop: args.data.parentPop
          ? {
              connect: args.data.parentPop,
            }
          : undefined,

        reseller: args.data.reseller
          ? {
              connect: args.data.reseller,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Pop)
  @nestAccessControl.UseRoles({
    resource: "Pop",
    action: "update",
    possession: "any",
  })
  async updatePop(@graphql.Args() args: UpdatePopArgs): Promise<Pop | null> {
    try {
      return await this.service.updatePop({
        ...args,
        data: {
          ...args.data,

          area: args.data.area
            ? {
                connect: args.data.area,
              }
            : undefined,

          parentPop: args.data.parentPop
            ? {
                connect: args.data.parentPop,
              }
            : undefined,

          reseller: args.data.reseller
            ? {
                connect: args.data.reseller,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Pop)
  @nestAccessControl.UseRoles({
    resource: "Pop",
    action: "delete",
    possession: "any",
  })
  async deletePop(@graphql.Args() args: DeletePopArgs): Promise<Pop | null> {
    try {
      return await this.service.deletePop(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Customer], { name: "customers" })
  @nestAccessControl.UseRoles({
    resource: "Customer",
    action: "read",
    possession: "any",
  })
  async findCustomers(
    @graphql.Parent() parent: Pop,
    @graphql.Args() args: CustomerFindManyArgs
  ): Promise<Customer[]> {
    const results = await this.service.findCustomers(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Expense], { name: "expenses" })
  @nestAccessControl.UseRoles({
    resource: "Expense",
    action: "read",
    possession: "any",
  })
  async findExpenses(
    @graphql.Parent() parent: Pop,
    @graphql.Args() args: ExpenseFindManyArgs
  ): Promise<Expense[]> {
    const results = await this.service.findExpenses(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [ProductItem], { name: "products" })
  @nestAccessControl.UseRoles({
    resource: "ProductItem",
    action: "read",
    possession: "any",
  })
  async findProducts(
    @graphql.Parent() parent: Pop,
    @graphql.Args() args: ProductItemFindManyArgs
  ): Promise<ProductItem[]> {
    const results = await this.service.findProducts(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [PopRecharge], { name: "rechargeHistory" })
  @nestAccessControl.UseRoles({
    resource: "PopRecharge",
    action: "read",
    possession: "any",
  })
  async findRechargeHistory(
    @graphql.Parent() parent: Pop,
    @graphql.Args() args: PopRechargeFindManyArgs
  ): Promise<PopRecharge[]> {
    const results = await this.service.findRechargeHistory(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Pop], { name: "subPops" })
  @nestAccessControl.UseRoles({
    resource: "Pop",
    action: "read",
    possession: "any",
  })
  async findSubPops(
    @graphql.Parent() parent: Pop,
    @graphql.Args() args: PopFindManyArgs
  ): Promise<Pop[]> {
    const results = await this.service.findSubPops(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Area, {
    nullable: true,
    name: "area",
  })
  @nestAccessControl.UseRoles({
    resource: "Area",
    action: "read",
    possession: "any",
  })
  async getArea(@graphql.Parent() parent: Pop): Promise<Area | null> {
    const result = await this.service.getArea(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Pop, {
    nullable: true,
    name: "parentPop",
  })
  @nestAccessControl.UseRoles({
    resource: "Pop",
    action: "read",
    possession: "any",
  })
  async getParentPop(@graphql.Parent() parent: Pop): Promise<Pop | null> {
    const result = await this.service.getParentPop(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Reseller, {
    nullable: true,
    name: "reseller",
  })
  @nestAccessControl.UseRoles({
    resource: "Reseller",
    action: "read",
    possession: "any",
  })
  async getReseller(@graphql.Parent() parent: Pop): Promise<Reseller | null> {
    const result = await this.service.getReseller(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
