/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Pop as PrismaPop,
  Customer as PrismaCustomer,
  Expense as PrismaExpense,
  ProductItem as PrismaProductItem,
  PopRecharge as PrismaPopRecharge,
  Area as PrismaArea,
  Reseller as PrismaReseller,
} from "@prisma/client";

export class PopServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.PopCountArgs, "select">): Promise<number> {
    return this.prisma.pop.count(args);
  }

  async pops(args: Prisma.PopFindManyArgs): Promise<PrismaPop[]> {
    return this.prisma.pop.findMany(args);
  }
  async pop(args: Prisma.PopFindUniqueArgs): Promise<PrismaPop | null> {
    return this.prisma.pop.findUnique(args);
  }
  async createPop(args: Prisma.PopCreateArgs): Promise<PrismaPop> {
    return this.prisma.pop.create(args);
  }
  async updatePop(args: Prisma.PopUpdateArgs): Promise<PrismaPop> {
    return this.prisma.pop.update(args);
  }
  async deletePop(args: Prisma.PopDeleteArgs): Promise<PrismaPop> {
    return this.prisma.pop.delete(args);
  }

  async findCustomers(
    parentId: string,
    args: Prisma.CustomerFindManyArgs
  ): Promise<PrismaCustomer[]> {
    return this.prisma.pop
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .customers(args);
  }

  async findExpenses(
    parentId: string,
    args: Prisma.ExpenseFindManyArgs
  ): Promise<PrismaExpense[]> {
    return this.prisma.pop
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .expenses(args);
  }

  async findProducts(
    parentId: string,
    args: Prisma.ProductItemFindManyArgs
  ): Promise<PrismaProductItem[]> {
    return this.prisma.pop
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .products(args);
  }

  async findRechargeHistory(
    parentId: string,
    args: Prisma.PopRechargeFindManyArgs
  ): Promise<PrismaPopRecharge[]> {
    return this.prisma.pop
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .rechargeHistory(args);
  }

  async findSubPops(
    parentId: string,
    args: Prisma.PopFindManyArgs
  ): Promise<PrismaPop[]> {
    return this.prisma.pop
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .subPops(args);
  }

  async getArea(parentId: string): Promise<PrismaArea | null> {
    return this.prisma.pop
      .findUnique({
        where: { id: parentId },
      })
      .area();
  }

  async getParentPop(parentId: string): Promise<PrismaPop | null> {
    return this.prisma.pop
      .findUnique({
        where: { id: parentId },
      })
      .parentPop();
  }

  async getReseller(parentId: string): Promise<PrismaReseller | null> {
    return this.prisma.pop
      .findUnique({
        where: { id: parentId },
      })
      .reseller();
  }
}
