/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field, Float } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsNumber,
  Max,
  IsEnum,
} from "class-validator";
import { AreaWhereUniqueInput } from "../../area/base/AreaWhereUniqueInput";
import { Type } from "class-transformer";
import { Decimal } from "decimal.js";
import { CustomerCreateNestedManyWithoutPopsInput } from "./CustomerCreateNestedManyWithoutPopsInput";
import { ExpenseCreateNestedManyWithoutPopsInput } from "./ExpenseCreateNestedManyWithoutPopsInput";
import { PopWhereUniqueInput } from "./PopWhereUniqueInput";
import { ProductItemCreateNestedManyWithoutPopsInput } from "./ProductItemCreateNestedManyWithoutPopsInput";
import { PopRechargeCreateNestedManyWithoutPopsInput } from "./PopRechargeCreateNestedManyWithoutPopsInput";
import { ResellerWhereUniqueInput } from "../../reseller/base/ResellerWhereUniqueInput";
import { PopCreateNestedManyWithoutPopsInput } from "./PopCreateNestedManyWithoutPopsInput";
import { EnumPopType } from "./EnumPopType";

@InputType()
class PopCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: () => AreaWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AreaWhereUniqueInput)
  @IsOptional()
  @Field(() => AreaWhereUniqueInput, {
    nullable: true,
  })
  area?: AreaWhereUniqueInput | null;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @Field(() => Float)
  balance!: Decimal;

  @ApiProperty({
    required: false,
    type: () => CustomerCreateNestedManyWithoutPopsInput,
  })
  @ValidateNested()
  @Type(() => CustomerCreateNestedManyWithoutPopsInput)
  @IsOptional()
  @Field(() => CustomerCreateNestedManyWithoutPopsInput, {
    nullable: true,
  })
  customers?: CustomerCreateNestedManyWithoutPopsInput;

  @ApiProperty({
    required: false,
    type: () => ExpenseCreateNestedManyWithoutPopsInput,
  })
  @ValidateNested()
  @Type(() => ExpenseCreateNestedManyWithoutPopsInput)
  @IsOptional()
  @Field(() => ExpenseCreateNestedManyWithoutPopsInput, {
    nullable: true,
  })
  expenses?: ExpenseCreateNestedManyWithoutPopsInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: () => PopWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PopWhereUniqueInput)
  @IsOptional()
  @Field(() => PopWhereUniqueInput, {
    nullable: true,
  })
  parentPop?: PopWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ProductItemCreateNestedManyWithoutPopsInput,
  })
  @ValidateNested()
  @Type(() => ProductItemCreateNestedManyWithoutPopsInput)
  @IsOptional()
  @Field(() => ProductItemCreateNestedManyWithoutPopsInput, {
    nullable: true,
  })
  products?: ProductItemCreateNestedManyWithoutPopsInput;

  @ApiProperty({
    required: false,
    type: () => PopRechargeCreateNestedManyWithoutPopsInput,
  })
  @ValidateNested()
  @Type(() => PopRechargeCreateNestedManyWithoutPopsInput)
  @IsOptional()
  @Field(() => PopRechargeCreateNestedManyWithoutPopsInput, {
    nullable: true,
  })
  rechargeHistory?: PopRechargeCreateNestedManyWithoutPopsInput;

  @ApiProperty({
    required: false,
    type: () => ResellerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ResellerWhereUniqueInput)
  @IsOptional()
  @Field(() => ResellerWhereUniqueInput, {
    nullable: true,
  })
  reseller?: ResellerWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => PopCreateNestedManyWithoutPopsInput,
  })
  @ValidateNested()
  @Type(() => PopCreateNestedManyWithoutPopsInput)
  @IsOptional()
  @Field(() => PopCreateNestedManyWithoutPopsInput, {
    nullable: true,
  })
  subPops?: PopCreateNestedManyWithoutPopsInput;

  @ApiProperty({
    required: true,
    enum: EnumPopType,
  })
  @IsEnum(EnumPopType)
  @Field(() => EnumPopType)
  type!: "MAIN" | "RESELLER" | "SUB_POP";
}

export { PopCreateInput as PopCreateInput };
