/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ResellerRechargeLog } from "./ResellerRechargeLog";
import { ResellerRechargeLogCountArgs } from "./ResellerRechargeLogCountArgs";
import { ResellerRechargeLogFindManyArgs } from "./ResellerRechargeLogFindManyArgs";
import { ResellerRechargeLogFindUniqueArgs } from "./ResellerRechargeLogFindUniqueArgs";
import { CreateResellerRechargeLogArgs } from "./CreateResellerRechargeLogArgs";
import { UpdateResellerRechargeLogArgs } from "./UpdateResellerRechargeLogArgs";
import { DeleteResellerRechargeLogArgs } from "./DeleteResellerRechargeLogArgs";
import { Reseller } from "../../reseller/base/Reseller";
import { ResellerRechargeLogService } from "../resellerRechargeLog.service";
@graphql.Resolver(() => ResellerRechargeLog)
export class ResellerRechargeLogResolverBase {
  constructor(protected readonly service: ResellerRechargeLogService) {}

  async _resellerRechargeLogsMeta(
    @graphql.Args() args: ResellerRechargeLogCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ResellerRechargeLog])
  async resellerRechargeLogs(
    @graphql.Args() args: ResellerRechargeLogFindManyArgs
  ): Promise<ResellerRechargeLog[]> {
    return this.service.resellerRechargeLogs(args);
  }

  @graphql.Query(() => ResellerRechargeLog, { nullable: true })
  async resellerRechargeLog(
    @graphql.Args() args: ResellerRechargeLogFindUniqueArgs
  ): Promise<ResellerRechargeLog | null> {
    const result = await this.service.resellerRechargeLog(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ResellerRechargeLog)
  async createResellerRechargeLog(
    @graphql.Args() args: CreateResellerRechargeLogArgs
  ): Promise<ResellerRechargeLog> {
    return await this.service.createResellerRechargeLog({
      ...args,
      data: {
        ...args.data,

        reseller: {
          connect: args.data.reseller,
        },
      },
    });
  }

  @graphql.Mutation(() => ResellerRechargeLog)
  async updateResellerRechargeLog(
    @graphql.Args() args: UpdateResellerRechargeLogArgs
  ): Promise<ResellerRechargeLog | null> {
    try {
      return await this.service.updateResellerRechargeLog({
        ...args,
        data: {
          ...args.data,

          reseller: {
            connect: args.data.reseller,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ResellerRechargeLog)
  async deleteResellerRechargeLog(
    @graphql.Args() args: DeleteResellerRechargeLogArgs
  ): Promise<ResellerRechargeLog | null> {
    try {
      return await this.service.deleteResellerRechargeLog(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Reseller, {
    nullable: true,
    name: "reseller",
  })
  async getReseller(
    @graphql.Parent() parent: ResellerRechargeLog
  ): Promise<Reseller | null> {
    const result = await this.service.getReseller(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
