/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ResellerRechargeLogService } from "../resellerRechargeLog.service";
import { ResellerRechargeLogCreateInput } from "./ResellerRechargeLogCreateInput";
import { ResellerRechargeLog } from "./ResellerRechargeLog";
import { ResellerRechargeLogFindManyArgs } from "./ResellerRechargeLogFindManyArgs";
import { ResellerRechargeLogWhereUniqueInput } from "./ResellerRechargeLogWhereUniqueInput";
import { ResellerRechargeLogUpdateInput } from "./ResellerRechargeLogUpdateInput";

export class ResellerRechargeLogControllerBase {
  constructor(protected readonly service: ResellerRechargeLogService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ResellerRechargeLog })
  @swagger.ApiBody({
    type: ResellerRechargeLogCreateInput,
  })
  async createResellerRechargeLog(
    @common.Body() data: ResellerRechargeLogCreateInput
  ): Promise<ResellerRechargeLog> {
    return await this.service.createResellerRechargeLog({
      data: {
        ...data,

        reseller: {
          connect: data.reseller,
        },
      },
      select: {
        amount: true,
        date: true,
        id: true,
        note: true,

        reseller: {
          select: {
            id: true,
          },
        },

        type: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ResellerRechargeLog] })
  @ApiNestedQuery(ResellerRechargeLogFindManyArgs)
  async resellerRechargeLogs(
    @common.Req() request: Request
  ): Promise<ResellerRechargeLog[]> {
    const args = plainToClass(ResellerRechargeLogFindManyArgs, request.query);
    return this.service.resellerRechargeLogs({
      ...args,
      select: {
        amount: true,
        date: true,
        id: true,
        note: true,

        reseller: {
          select: {
            id: true,
          },
        },

        type: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ResellerRechargeLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async resellerRechargeLog(
    @common.Param() params: ResellerRechargeLogWhereUniqueInput
  ): Promise<ResellerRechargeLog | null> {
    const result = await this.service.resellerRechargeLog({
      where: params,
      select: {
        amount: true,
        date: true,
        id: true,
        note: true,

        reseller: {
          select: {
            id: true,
          },
        },

        type: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ResellerRechargeLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiBody({
    type: ResellerRechargeLogUpdateInput,
  })
  async updateResellerRechargeLog(
    @common.Param() params: ResellerRechargeLogWhereUniqueInput,
    @common.Body() data: ResellerRechargeLogUpdateInput
  ): Promise<ResellerRechargeLog | null> {
    try {
      return await this.service.updateResellerRechargeLog({
        where: params,
        data: {
          ...data,

          reseller: {
            connect: data.reseller,
          },
        },
        select: {
          amount: true,
          date: true,
          id: true,
          note: true,

          reseller: {
            select: {
              id: true,
            },
          },

          type: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ResellerRechargeLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteResellerRechargeLog(
    @common.Param() params: ResellerRechargeLogWhereUniqueInput
  ): Promise<ResellerRechargeLog | null> {
    try {
      return await this.service.deleteResellerRechargeLog({
        where: params,
        select: {
          amount: true,
          date: true,
          id: true,
          note: true,

          reseller: {
            select: {
              id: true,
            },
          },

          type: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
